import type { DestinationDefinition, DestinationKey } from './types';

/** The sole source of mobile destination metadata. Only native screens with an implemented access contract belong here. */
export const destinationRegistry = {
  home: { key: 'home', routeName: 'HomeTab', label: 'Home', icon: 'home-outline', activeIcon: 'home', priority: 10, group: 'primary', allowedRoles: ['participant'], requiredPermissions: [], featureFlag: null, badgeSource: null, implementationStatus: 'implemented' },
  journey: { key: 'journey', routeName: 'JourneyTab', label: 'Journey', icon: 'map-outline', activeIcon: 'map', priority: 20, group: 'primary', allowedRoles: ['participant'], requiredPermissions: [], featureFlag: null, badgeSource: null, implementationStatus: 'implemented' },
  sessions: { key: 'sessions', routeName: 'SessionsTab', label: 'Sessions', icon: 'videocam-outline', activeIcon: 'videocam', priority: 30, group: 'primary', allowedRoles: ['participant'], requiredPermissions: [], featureFlag: null, badgeSource: null, implementationStatus: 'implemented' },
  notifications: { key: 'notifications', routeName: 'NotificationsTab', label: 'Alerts', icon: 'notifications-outline', activeIcon: 'notifications', priority: 40, group: 'primary', allowedRoles: ['participant', 'participant_retailer'], requiredPermissions: ['notifications:read'], featureFlag: null, badgeSource: 'unread-notifications', implementationStatus: 'implemented' },
  more: { key: 'more', routeName: 'MoreTab', label: 'More', icon: 'menu-outline', activeIcon: 'menu', priority: 90, group: 'primary', allowedRoles: ['participant', 'participant_retailer'], requiredPermissions: [], featureFlag: null, badgeSource: null, implementationStatus: 'implemented' },
  profile: { key: 'profile', routeName: 'ProfileStack', label: 'My Profile', icon: 'person-circle-outline', priority: 10, group: 'more', allowedRoles: ['participant', 'participant_retailer'], requiredPermissions: [], featureFlag: null, badgeSource: null, implementationStatus: 'implemented' },
  assessments: { key: 'assessments', routeName: 'AssessmentsList', label: 'Assessments', icon: 'school-outline', priority: 20, group: 'more', allowedRoles: ['participant'], requiredPermissions: ['assessments:read'], featureFlag: null, badgeSource: null, implementationStatus: 'implemented' },
  'activity-detail': { key: 'activity-detail', routeName: 'ActivityDetail', label: 'Activity detail', icon: 'document-text-outline', priority: 10, group: 'contextual', allowedRoles: ['participant'], requiredPermissions: [], featureFlag: null, badgeSource: null, implementationStatus: 'implemented' },
  'session-detail': { key: 'session-detail', routeName: 'SessionDetail', label: 'Session detail', icon: 'videocam-outline', priority: 20, group: 'contextual', allowedRoles: ['participant'], requiredPermissions: ['sessions:read'], featureFlag: null, badgeSource: null, implementationStatus: 'implemented' },
  'assessment-intro': { key: 'assessment-intro', routeName: 'AssessmentIntro', label: 'Assessment', icon: 'school-outline', priority: 30, group: 'contextual', allowedRoles: ['participant'], requiredPermissions: ['assessments:read'], featureFlag: null, badgeSource: null, implementationStatus: 'implemented' },
  'assessment-attempt': { key: 'assessment-attempt', routeName: 'AssessmentAttempt', label: 'Assessment attempt', icon: 'create-outline', priority: 40, group: 'contextual', allowedRoles: ['participant'], requiredPermissions: ['assessments:read'], featureFlag: null, badgeSource: null, implementationStatus: 'implemented' },
  'assessment-result': { key: 'assessment-result', routeName: 'AssessmentResult', label: 'Assessment result', icon: 'ribbon-outline', priority: 50, group: 'contextual', allowedRoles: ['participant'], requiredPermissions: ['assessments:read'], featureFlag: null, badgeSource: null, implementationStatus: 'implemented' },
} as const satisfies Record<DestinationKey, DestinationDefinition>;

export const destinationDefinitions = Object.values(destinationRegistry) as readonly DestinationDefinition[];
