import React from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import type { ActivityDTO, SubmissionDTO } from '../types/api';
import { colors, fontFamily, radii, spacing } from '../theme';
import { StatusBadge } from './StatusBadge';
import { isActivityDone, titleCase } from '../utils/activities';

type Props={activity:ActivityDTO;submission:SubmissionDTO|null;onPress:()=>void;phaseTitle?:string};
const icons:Record<string,React.ComponentProps<typeof Ionicons>['name']>={assessment:'clipboard-outline',video:'play-circle-outline',pdf:'document-text-outline',case_study:'book-outline',content:'book-outline',survey:'bar-chart-outline',coaching:'people-outline',capstone:'flag-outline',discussion:'chatbubbles-outline',feedback_360:'sync-outline',journal:'create-outline',assignment:'document-attach-outline',peer_review:'people-outline'};
export function JourneyActivityCard({activity,submission,onPress,phaseTitle}:Props){const done=isActivityDone(activity,{[activity.id]:submission});const locked=!!activity.locked;const active=!done&&!locked;const status=done?'completed':locked?'locked':active?'active':'pending';const action=done?'View':locked?'Locked':submission?'Resume':'Open';return <Pressable accessibilityRole="button" accessibilityLabel={`${activity.title}. ${locked?'Locked':done?'Completed':'Open activity'}`} accessibilityState={{disabled:locked}} disabled={locked} onPress={onPress} style={({pressed})=>[styles.card,done&&styles.done,locked&&styles.locked,pressed&&!locked&&styles.pressed]}><View style={[styles.icon,{backgroundColor:done?'rgba(34,197,94,0.10)':'rgba(200,168,96,0.10)'}]}><Ionicons name={locked?'lock-closed-outline':icons[activity.type]??'book-outline'} size={20} color={done?colors.status.success:locked?colors.status.inactive:colors.brand.gold}/></View><View style={styles.copy}><View style={styles.titleRow}><Text numberOfLines={2} style={styles.title}>{activity.title}</Text>{activity.is_mandatory?<StatusBadge status="pending" label="Required"/>:null}</View><Text numberOfLines={1} style={styles.meta}>{phaseTitle?`${phaseTitle} · `:''}{titleCase(activity.type.replaceAll('_',' '))} · {activity.duration_mins||30} min</Text>{activity.description?<Text numberOfLines={2} style={styles.description}>{activity.description}</Text>:null}{locked?<Text numberOfLines={2} style={styles.lockReason}>{activity.locked_reason||'This activity is not available yet.'}</Text>:null}</View><View style={styles.trailing}>{done?<Ionicons name="checkmark-circle" size={22} color={colors.status.success}/>:locked?<StatusBadge status="locked"/>:<Text style={styles.action}>{action}</Text>}</View></Pressable>}
const styles=StyleSheet.create({card:{minHeight:84,flexDirection:'row',alignItems:'center',gap:spacing.md,padding:spacing.md,borderRadius:radii.card,borderWidth:1,borderColor:colors.surface.border,backgroundColor:colors.surface.card},done:{backgroundColor:'rgba(34,197,94,0.04)',borderColor:'rgba(34,197,94,0.22)'},locked:{backgroundColor:colors.surface.alt},pressed:{backgroundColor:'rgba(200,168,96,0.08)'},icon:{width:42,height:42,borderRadius:10,alignItems:'center',justifyContent:'center'},copy:{flex:1,minWidth:0},titleRow:{flexDirection:'row',alignItems:'flex-start',gap:spacing.sm},title:{flex:1,fontFamily:fontFamily.bold,fontSize:13,color:colors.text.primary},meta:{fontFamily:fontFamily.medium,fontSize:10,color:colors.text.secondary,marginTop:4,textTransform:'capitalize'},description:{fontFamily:fontFamily.regular,fontSize:11,color:colors.text.secondary,marginTop:4,lineHeight:15},lockReason:{fontFamily:fontFamily.medium,fontSize:10,color:colors.text.secondary,marginTop:4},trailing:{alignItems:'flex-end',justifyContent:'center'},action:{fontFamily:fontFamily.bold,fontSize:11,color:colors.brand.gold}});
